version: '3'
services:
  db:
    image: postgres:14.2-alpine
    container_name: tunespotdb_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  tunespot_web:
    build: .
    command: "bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - ./app:/app
      - ./config:/app/config
      - ./lib:/app/lib
      - ./log:/app/log
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./vendor:/app/vendor
      - music_db_storage:/app/storage
      - ~/Desktop/music_db:/app
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}
  music_db_storage: {}
